linters:
  enable-all: true
  exclude-use-default: false
  disable:
    - exhaustivestruct
    - forbidigo
    - golint
    - interfacer
    - ireturn
    - maligned
    - scopelint

linters-settings:
  varnamelen:
    ignore-names:
      - err
      - ts