name: "CI"

on:
  pull_request:
  push:
    branches:
    - '*'
    tags:
    - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.17.x", "1.18.x"]
        include:
        - go: 1.18.x
          latest: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Go Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
          artifacts/bin
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
            
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Download Dependencies
      run: |
        go mod download

    - name: Lint
      if: matrix.latest
      run: make lint

    - name: Run GolangCI-Lint
      uses: golangci/golangci-lint-action@v3.2.0
      with:
        skip-cache: true
        version: latest

    - name: Test
      run: make test

    - name: CI
      run: make ci
