name: "CI"

on:
  pull_request:
  push:
    branches:
    - '*'
    tags:
    - 'v*'

jobs:
  unit-test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Go Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
          artifacts/bin
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ^1
      id: go

    - name: Set up go env
      run: export PATH=${PATH}:`go env GOPATH`/bin

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3.1.0
      with:
        skip-cache: true
        version: latest

    - name: unit-test
      run: make test

    - name: ci
      run: make ci
